# fly.toml file generated for tgbotderbl on 2023-03-02T03:21:23Z

app = "geminiprobot"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
image = "ghcr.io/jackrun123/gemini-pro-bot:latest"

[env]

[experimental]
  auto_rollback = true

[[services]]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = false  # optional

[deploy]
  strategy = "immediate"